version: '3.8'

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=states-db
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/states-db
      - REDIS_HOST=redis
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge