version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: state-csv-batch-processor-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DEBUG=*
    volumes:
      - ./logs:/app/logs
    restart: on-failure
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    name: state-csv-batch-processor-network
    driver: bridge